name: test

on: [push, pull_request, workflow_dispatch]

jobs:
    test-job:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.9]
                poetry-version: [1.1.7]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: ${{ matrix.poetry-version }}
            - name: Install dependencies
              run: |
                  poetry install --no-root
            - name: Run checks
              run: |
                  poetry run flake8 --statistics --show-source
                  poetry run python3 -m unittest -k test_parse_input_file_returns_a_list_of_events
                  poetry run python3 -m unittest -k test_event_handler_default
                  poetry run python3 -m unittest -k test_event_handler_when_no_car_parking_lot
                  poetry run python3 -m unittest -k test_event_handler_when_no_motorcycle_parking_lot
                  poetry run python3 -m unittest -k test_parking_lots_are_filled_sequentially
                  poetry run python3 -m unittest -k test_create_parking_lot
